# SPDX-FileCopyrightText: Copyright 2026 Event Horizon Dotfiles
# SPDX-License-Identifier: MIT
name: Bug Report
description: Report a bug or issue with the dotfiles configuration
title: "[BUG]: "
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Read First

        **Please make sure your issue isn't already reported before creating a new one.**

        For support questions or help with configuration, please reach out on Discord or Discussions.

        When reporting bugs, please provide as much detail as possible to help us reproduce and fix the issue.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched for a similar issue in this repository and did not find one.
          required: true
        - label: I have read the [Reporting Guide](docs/reporting-issues.md) before submitting this issue.
          required: true
  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Detailed steps to reproduce the behavior"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen"
    validations:
      required: false
  - type: input
    id: distro
    attributes:
      label: Distro & Version
      placeholder: "Example: Arch Linux 6.12.1, Hyprland"
    validations:
      required: true
  - type: input
    id: hardware
    attributes:
      label: Hardware
      placeholder: "Example: AMD Ryzen 7 5800X, NVIDIA RTX 3080"
    validations:
      required: true
